- hosts: all
  sudo: yes
  tasks:
    - name: Install packages
      apt: name={{ item }} state=present update_cache=yes
      with_items: 
        - git
        - tmux
        - vim
        - ubuntu-gnome-desktop
        - build-essential
        - subversion
        - git
        - libmetis-dev
        - libscotch-dev
        - bison++
        - libginac-dev
        - libqt4-dev
        - autoconf
        - libboost-dev

    - name: Download qss-solver source
      subversion: repo=svn://svn.code.sf.net/p/qssengine/code-0/trunk dest=/usr/src/qssengine 

#    - name: Install a .deb package
#      apt: deb=/root/qss-solver-amd64.deb

#    - name: download qss-solver 
#      get_url: url=http://downloads.sourceforge.net/project/qssengine/3.0/qss-solver-amd64.deb dest=/root/qss-solver-amd64.deb mode=0440

    - name: Download modelica cc
      subversion: repo=svn://svn.code.sf.net/p/modelicacc/code/trunk dest=/usr/src/modelicacc-code

    - name: Download pd2mo source
      git : repo=https://github.com/lucciano/pd2mo.git dest=/usr/src/pd2mo

